# Server Configuration
server.port=9091
spring.servlet.multipart.max-file-size=30MB
spring.servlet.multipart.max-request-size=30MB

# DataSource Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/kyc_saving_and_current
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.auto-commit=false

# JPA Hibernate Configuration
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false
root.path=./uploads

jwt.secret=${JWT_SECRET}
jwt.expiration-ms=86400000

zoop.enabled=false

# Tomcat
server.tomcat.max-threads=100
server.tomcat.accept-count=100

# DB
spring.datasource.hikari.maximum-pool-size=30
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.connection-timeout=2000

# Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never