apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  DB_URL: amRiYzpwb3N0Z3Jlc3FsOi8vcG9zdGdyZXMtc2VydmljZTo1NDMyL2t5Y19zYXZpbmdfYW5kX2N1cnJlbnQ=
  DB_USERNAME: cG9zdGdyZXM=
  DB_PASSWORD: a3ljcGFzczEyMw==
  JWT_SECRET: YTRmOWIyYzNkOGU3ZjFhNmI1YzRkM2UyZjFhMDliOGM3ZDZlNWY0YTNiMmMxZDBlOWY4YTdiNmM1ZDRlM2YyYQ==